# Generated by Django 5.2.6 on 2025-12-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('empresa', models.CharField(max_length=200)),
                ('local', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('CLT', 'CLT'), ('PJ', 'PJ'), ('Freelancer', 'Freelancer'), ('Estágio', 'Estágio')], max_length=20)),
                ('descricao', models.TextField()),
                ('ativa', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
