# Generated by Django 5.2.6 on 2025-12-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_plano_assinatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinatura',
            name='data_fim',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
